from django.db import models

# Create your models here.
class City(models.Model):
    id = models.IntegerField(range(0,5), primary_key=True, default=0)
    city_name = models.CharField(max_length=20)
    cappucino = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    soda = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    milk_gallon = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    bread_loaf = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    rice_lb = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    eggs_dozen = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    cheese_lb = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    chicken_breast_lb = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    beef_lb = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    apples_lb = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    banana_lb = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    oranges_lb = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    tomato_lb = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    potato_lb = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    onion_lb = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    lettuce_lb = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    low_dineout = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    mid_dineout = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    fast_food = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    drink_price = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    internet_price = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    utility_price = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    lo_bed_price1 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    lo_bed_price2 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    lo_bed_price3 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    mid_bed_price1 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    mid_bed_price2 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    mid_bed_price3 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    hi_bed_price1 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    hi_bed_price2 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    hi_bed_price3 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    stud_bed_price1 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    stud_bed_price2 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    stud_bed_price3 = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    stud_price = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    health_insurance = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    gas_gallon = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    miles_driven = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    bus_pass = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    miles_driven = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    bus_pass = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    sales_tax = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    movie_price = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    sports_leisure_price = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    parking_price = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    auto_insurance = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    auto_maintenance_price = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    auto_tax = models.DecimalField(max_digits=10, decimal_places=5, default=0)



